name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      build_success: ${{ steps.build_step.outputs.success }}
      build_id: ${{ steps.build_step.outputs.build_id }}
    strategy:
      matrix:
        os:
          - ubuntu-${{ vars.UBUNTU_VERSION }}
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libboost-all-dev

      - name: Configure and build
        id: build_step
        run: |
          chmod +x scripts/build/build.sh
          ./scripts/build/build.sh --type ${{ matrix.build_type }} --clean --test
          echo "success=true" >> $GITHUB_OUTPUT
          echo "build_id=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thales-${{ matrix.os }}-${{ matrix.build_type }}
          path: |
            build/
            !build/_deps/**/*
            !build/CMakeFiles/**/*
            !build/Testing/**/*
          if-no-files-found: error
          retention-days: 1
